### ISSUE TITLE
组件里 onInit 会加载多次，以及其它BUG

### ISSUE THREAD

**Issue by byends** [RubyLouvre/avalon#1435]
**avalon 版本：`/*! built in 2016-6-7:11 version 2.07 by 司徒正美 */`**
  
2016-06-08 23:14 更新

  
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>确认订单</title>
    <link href="./main.css" rel="stylesheet">
    <script src="./avalon.js"></script>
</head>
<body>
<div class="container" ms-controller="container">
    <div class="loading-wrap" ms-visible="@loadingWrapShow">数据加载中....</div>
    <xmp ms-widget="{is:'ms-container'}"></xmp>
</div>
<script>
function heredoc(fn) {
    return fn.toString().replace(/^[^\/]+\/\*!?\s?/, '').
            replace(/\*\/[^\/]+$/, '').trim().replace(/>\s*</g, '><')
}

var container = heredoc(function() {
/*
<div>
  <xmp ms-widget="[{is:'ms-address-wrap', $id:'address'}]"></xmp>
</div>

*/
})


// 主容器
var vmContainer = avalon.define({
    $id: 'container',
    loadingWrapShow: true
})

avalon.component('ms-container', {
  template: container,
  defaults: {
  }
})

var addressTmpl = heredoc(function() {
/*
<div class="address-wrap ms-controller" ms-visible="@addressWrapShow">
    <div class="wrap-header">
        <h3>选择收货地址</h3>
        <span class="small-text">美的商城配送方式：快递（免运费）</span>
        <a class="right-text" href="javascript:;" ms-click="@addressListExpand = !@addressListExpand" ms-visible="@addressTotal > 3">
            <span ms-visible="!@addressListExpand">展开</span><span ms-visible="@addressListExpand">收起</span>更多收货地址<i class="icon_arrow_bottom" ms-class="{icon_arrow_top: @addressListExpand}"></i></a>
    </div>
    <div class="address-box">
        <!--ms-for:(index, el) in @addressList-->
        <div class="adr"
             ms-class="{'default': (el.nIsDefault == 1 ? (@checkDefault(el) && true) : false), 'checked': (@addressChecked.lAddrId == el.lAddrId), hide: (index > 2 && ! @addressListExpand)}"
             ms-hover="'hover'"
             ms-click="@addressChecked = el">
            <div class="adr-inner" ms-attr="{title: (el.strProvince + el.strCity + ' ' + el.strPersonName)}">
                <i class="icon_checked"></i>
                <div class="adr-head" >
                    <span class="adr-province" ms-text="el.strProvince"></span>
                    <span class="adr-city" ms-text="el.strCity"></span>
                    <span class="adr-name" ms-text="el.strPersonName"></span>
                </div>
                <div class="adr-body" ms-attr="{title: (el.strArea + el.strDetailMsg + ' ' + el.strMobileNum)}">
                    <p class="adr-text">
                        <span class="adr-county" ms-text="el.strArea"></span>
                        <span class="adr-detail" ms-text="el.strDetailMsg"></span>
                        <span class="adr-tel" ms-text="el.strMobileNum"></span>
                        <span class="adr-default-text">[默认]</span>
                    </p>
                </div>
                <div class="adr-foot">
                    <a href="javascript:;" ms-click="@editAdrress(el, $event) | stop">编辑</a>
                    <a href="javascript:;" ms-click="@deleteAddress(el, $event) | stop">删除</a>
                </div>
            </div>
        </div>
        <!--ms-for-end:-->

        <div class="adr" ms-hover="'hover'" ms-click="@editAdrress({}, $event)">
            <div class="adr-inner">
                <div class="adr-add">
                    <p class="adr-add-icon"><i class="icon_add"></i></p>
                    <p class="adr-add-text">添加地址</p>
                </div>
            </div>
        </div>
    </div>
    <xmp ms-widget="[{is:'mdui-dialog', $id:'addressDeleteDialog'}, @dialogAddressDeleteConf]">

    </xmp>
    <xmp ms-widget="[{is:'mdui-dialog', $id:'addressEditDialog'}, @dialogAddressEditConf]">
        <div slot="body">

            <div class="btn-box">
                <div class="addr-btn blue" ms-click="@confirmDialog | stop">保存</div>
                <div class="addr-btn" ms-click="@closeDialog | stop">取消</div>
            </div>
        </div>
        <div slot="foot"></div>
    </xmp>
</div>
*/
})

avalon.component('ms-address-wrap', {
    template: addressTmpl,
    defaults: {
        addressChecked: {},
        addressDelete: {},
        defaultAddressEdit: {
            lAddrId: '',
            strArea: '',
            strAreaCode: '',
            strCity: '',
            strCityCode: '',
            strDetailMsg: '',
            strMobileNum: '',
            strPersonName: '',
            strProvince: '',
            strProvinceCode: ''
        },
        addressEdit: {},
        addressListExpand: false,
        addressList: [],
        addressTotal: 0,
        addressWrapShow: false,
        dialogAddressDeleteConf: {
            dialogType: 'confirm', // confirm info tips
            dialogIcon: 'info',
            dialogShow: false,
            onConfirm: function(e) {
                avalon.log('AddressDelete confirm')
            },
            onClose: function() {
                avalon.log('AddressDelete close')
            }
        },
        dialogAddressEditConf: {
            dialogType: 'confirm', // confirm info tips
            dialogIcon: false,
            dialogWrapCss: {width: 800},
            dialogShow: false,
            onConfirm: function(e) {
                avalon.log('AddressEdit confirm')
            },
            onClose: function() {
                avalon.log('AddressEdit close')
            }
        },
        // 选中默认地址
        checkDefault: function (addr) {
            if (! this.addressChecked.lAddrId) {
                this.addressChecked = addr
            }
        },
        // 获取地址列表数据
        getAll: function() {
            this.addressList = [{"lAddrId":10677,"lUin":12070,"strPersonName":"\u6ee8\u6cb31","strMobileNum":"11111111111","strProvince":"\u5e7f\u4e1c\u7701","strProvinceCode":"440000","strCity":"\u6df1\u5733\u5e02","strCityCode":"440300","strArea":"\u798f\u7530\u533a","strAreaCode":"440304","strDetailMsg":"\u6ee8\u6cb3\u6ee8\u6cb3\u6ee8\u6cb3\u6ee8\u6cb3\u6ee8\u6cb3\u6ee8\u6cb3\u6ee8\u6cb3\u6ee8\u6cb3","nIsDefault":1},{"lAddrId":10724,"lUin":12070,"strPersonName":"\u8fdb\u57ce\u4e0d3\u70c33\u4e2d\u5730\u7c89\u5730","strMobileNum":"11111111111","strProvince":"\u6cb3\u5317\u7701","strProvinceCode":"130000","strCity":"\u77f3\u5bb6\u5e84\u5e02","strCityCode":"130100","strArea":"\u957f\u5b89\u533a","strAreaCode":"130102","strDetailMsg":"12321321313213","nIsDefault":null},{"lAddrId":10725,"lUin":12070,"strPersonName":"\u9648\u6d69","strMobileNum":"18611111111","strProvince":"\u5317\u4eac\u5e02","strProvinceCode":"110000","strCity":"\u5317\u4eac\u5e02","strCityCode":"110100","strArea":"\u4e1c\u57ce\u533a","strAreaCode":"110101","strDetailMsg":"\u5b66\u5e9c\u8def\u6021\u5316\u91d1\u878d\u79d1\u6280\u5927\u53a623\u697c","nIsDefault":null},{"lAddrId":10726,"lUin":12070,"strPersonName":"\u6d82\u6d82","strMobileNum":"18611111111","strProvince":"\u5c71\u897f\u7701","strProvinceCode":"140000","strCity":"\u5927\u540c\u5e02","strCityCode":"140200","strArea":"\u5357\u90ca\u533a","strAreaCode":"140211","strDetailMsg":"\u7389\u5f8b\u8def\u82b1\u6837\u5e74\u82b1\u4e61A\u680b9O","nIsDefault":null},{"lAddrId":10727,"lUin":12070,"strPersonName":"\u840c\u840c","strMobileNum":"18611111111","strProvince":"\u6cb3\u5317\u7701","strProvinceCode":"130000","strCity":"\u5510\u5c71\u5e02","strCityCode":"130200","strArea":"\u8def\u5357\u533a","strAreaCode":"130202","strDetailMsg":"\u6d77\u79c0\u8def21\u53f7\u9f99\u5149\u4e16\u7eaa\u5927\u53a6B\u5ea711\u697c","nIsDefault":null}];
            this.addressTotal = this.addressList.length
            this.addressWrapShow = true
            this.loadingWrapShow = false
        },
        // 弹出确认删除浮层
        deleteAddress: function(addr, e) {
            this.addressDelete = addr
            this.dialogAddressDeleteConf.dialogShow = ! this.dialogAddressDeleteConf.dialogShow
        },
        // 弹出地址编辑浮层
        editAdrress: function(addr, e) {
            var self = this
            self.dialogAddressEditConf.dialogShow = ! self.dialogAddressEditConf.dialogShow
        },
        onInit: function() {
            var self = this
            setTimeout(function() {
                self.getAll.call(self)
            }, 3000)

            this.addressEdit = avalon.mix({}, this.defaultAddressEdit)
            avalon.log('onInit 会加载多次')
        }
    }
})


var dialogTmpl = heredoc(function() {
/*
<div>
  <div class="mdui-dialog-mask" ms-visible="@dialogShow" ms-if="@dialogMask"></div>
  <div class="mdui-dialog"
    ms-css="@dialogWrapCss"
    ms-class="['mdui-dialog-' + @dialogType, @dialogWrapClass]"
    ms-visible="@dialogShow">
    <a class="mdui-dialog-close" href="javascript:;"
        ms-click="@closeDialog"
        ms-if="@dialogType != 'tips' && @dialogCloseXShow">&times;</a>
    <i ms-class="['mdui-dialog-icon-' + @dialogIcon]" ms-if="@dialogIcon"></i>
    <div class="mdui-dialog-confirm-content" ms-if="@dialogType != 'tips'">
        <div class="mdui-dialog-head" ms-visible="@dialogHeadShow">
          <slot name="head"></slot>
        </div>
        <div class="mdui-dialog-body" ms-visible="@dialogBodyShow">
            <slot name="body"></slot>
        </div>
        <div class="mdui-dialog-foot mdui-dialog-btns-inline"
            ms-class="['mdui-dialog-btns-inline' + @dialogFootBtnNum]"
            ms-visible="@dialogFootShow">
            <slot name="foot">
                <a class="mdui-dialog-btn" href="javascript:void(0)" ms-click="@confirmDialog">确 认</a>
                <a class="mdui-dialog-btn" href="javascript:void(0)" ms-click="@closeDialog">取 消</a>
            </slot>
        </div>
    </div>
    <div class="mdui-dialog-tips-content" ms-if="@dialogType == 'tips'">
        <slot name="content">正在加载中，请稍候......</slot>
    </div>
  </div>
</div>
*/
})

// 组件定义
avalon.component('mdui-dialog', {
  template: dialogTmpl,
  defaults: {
    dialogType: 'confirm', // confirm info tips
    dialogIcon: 'info', // info  success
    dialogWrapClass: '', // 指定额外的 dialog 容器 class
    dialogWrapCss: {}, // // 指定额外的 dialog 容器 css
    dialogShow: false,
    dialogCloseXShow: true,
    dialogHeadShow: true,
    dialogBodyShow: true,
    dialogFootShow: true,
    dialogMask: true,
    dialogFootBtnNum: 0, // 底部按钮个数
    confirmDialog: function(e) {
        var result = this.onConfirm(e, this)

        if (result !== false) {
            this.dialogShow = ! this.dialogShow
        }
    },
    closeDialog: function(e) {
        this.onClose(e, this)
        this.dialogShow = ! this.dialogShow
    },
    onConfirm: avalon.noop,
    onShow: avalon.noop,
    onClose: avalon.noop,

    onInit: function(e) {
    },
    onReady: function(e) {
        //this.dialogFootBtnNum = $(e.target).find('.mdui-dialog-foot a').length
        this.onShow(e, this)
    },
    onViewChange: function(e) {
        // var $dialog =  $(e.target).find('.mdui-dialog')
        // var top = - Math.floor($dialog.height() / 2) - 100
        // var left = - Math.floor($dialog.width() / 2)
        // $dialog.css({'margin-top': top, 'margin-left': left})
    }
  }
})

</script>
</body>
</html>


```

**Comment by byends** [comment]
css 代码：
```css
.addr-btn {
  display: inline-block;
  *display: inline;
  *zoom: 1; }

.adr-table .form-text, .addr-btn {
  -webkit-box-sizing: border-box;
  box-sizing: border-box; }

.adr-table {
  color: #333;
  margin: 15px 0 40px;
  width: 100%; }
  .adr-table td,
  .adr-table th {
    padding: 5px 0;
    vertical-align: middle; }
  .adr-table th {
    width: 20%;
    text-align: right;
    font-weight: 400;
    position: relative; }
  .adr-table td {
    padding-left: 20px;
    text-align: left; }
  .adr-table .ipt-box {
    width: 100%; }
    .adr-table .ipt-box .form-text {
      width: 80%; }
    .adr-table .ipt-box textarea {
      resize: none; }
  .adr-table input::-webkit-input-placeholder {
    /* WebKit browsers */
    color: #ccc; }
  .adr-table input:-moz-placeholder {
    /* Mozilla Firefox 4 to 18 */
    color: #ccc; }
  .adr-table input::-moz-placeholder {
    /* Mozilla Firefox 19+ */
    color: #ccc; }
  .adr-table input:-ms-input-placeholder {
    /* Internet Explorer 10+ */
    color: #ccc; }
  .adr-table textarea::-webkit-input-placeholder {
    /* WebKit browsers */
    color: #ccc; }
  .adr-table textarea:-moz-placeholder {
    /* Mozilla Firefox 4 to 18 */
    color: #ccc; }
  .adr-table textarea::-moz-placeholder {
    /* Mozilla Firefox 19+ */
    color: #ccc; }
  .adr-table textarea:-ms-input-placeholder {
    /* Internet Explorer 10+ */
    color: #ccc; }
  .adr-table .text-error {
    position: absolute;
    color: #f30;
    top: 0;
    left: 70%;
    width: 35%;
    font-size: 12px;
    line-height: normal;
    padding: 10px 0 0 10px; }
  .adr-table .form-text {
    border: 1px solid #c8c8c8;
    padding: 0 10px;
    line-height: 38px;
    height: 38px;
    width: 100%; }
  .adr-table .address-detail {
    height: 75px;
    line-height: 1.6;
    padding: 10px;
    font-size: 12px;
    margin-bottom: -4px; }
  .adr-table .address-label {
    position: relative;
    top: -27px;
    *top: 0; }
  .adr-table .placeholder {
    color: #ccc; }
  .adr-table .address-placeholder {
    position: absolute;
    top: 10px;
    left: 10px; }
  .adr-table .ipt-placeholder {
    position: relative;
    top: 0;
    left: -410px; }
  .adr-table .star {
    color: red;
    position: relative;
    left: -5px; }

.btn-box {
  padding-bottom: 25px; }

.addr-btn {
  width: 100px;
  height: 40px;
  line-height: 40px;
  border: 1px solid #c8c8c8;
  text-align: center;
  letter-spacing: 5px;
  margin-right: 20px;
  cursor: pointer; }
  .addr-btn.blue {
    border: none;
    background: #0093d5;
    color: #fff;
    border: 0; }
  .addr-btn:hover {
    border-color: #999; }
    .addr-btn:hover.blue {
      background: #0086c2; }
.mdui-dialog {
  display: none;
  position: fixed;
  left: 50%;
  top: 50%;
  padding-top: 40px;
  background-color: #fff;
  border-radius: 3px;
  z-index: 1000;
  line-height: 1.5; }
  .mdui-dialog .text-center {
    text-align: center; }
  .mdui-dialog .text-prompt {
    font-size: 18px; }
  .mdui-dialog .text-red {
    color: #f30; }
  .mdui-dialog .text-gray {
    color: #999; }

.mdui-dialog-mask {
  position: fixed;
  left: 0;
  top: 0;
  height: 100%;
  width: 100%;
  background: #000;
  opacity: 0.2;
  filter: alpha(opacity=50);
  z-index: 999; }

.mdui-dialog-icon-info,
.mdui-dialog-icon-success {
  display: inline-block;
  *display: inline;
  *zoom: 1;
 }

.mdui-dialog-confirm,
.mdui-dialog-info {
  min-width: 360px;
  *width: 360px;
  *border: 1px solid #e6e6e6; }
  .mdui-dialog-confirm .mdui-dialog-icon-info,
  .mdui-dialog-confirm .mdui-dialog-icon-success,
  .mdui-dialog-info .mdui-dialog-icon-info,
  .mdui-dialog-info .mdui-dialog-icon-success {
    display: block;
    width: 48px;
    height: 48px;
    margin: 0 auto 20px; }
  .mdui-dialog-confirm .mdui-dialog-icon-info,
  .mdui-dialog-info .mdui-dialog-icon-info {
    background-position: 0 -49px; }
  .mdui-dialog-confirm .mdui-dialog-icon-success,
  .mdui-dialog-info .mdui-dialog-icon-success {
    background-position: 0 0; }

.mdui-dialog-tips {
  background-color: #000;
  color: #fff;
  padding: 10px 15px; }
  .mdui-dialog-tips.show {
    display: inline-block;
    *display: inline;
    *zoom: 1; }
  .mdui-dialog-tips .mdui-dialog-icon-info,
  .mdui-dialog-tips .mdui-dialog-icon-success {
    width: 16px;
    height: 16px;
    margin-right: 7px;
    vertical-align: -3px; }
  .mdui-dialog-tips .mdui-dialog-icon-success {
    background-position: -50px 0; }
  .mdui-dialog-tips .mdui-dialog-icon-info {
    background-position: -50px -17px; }
  .mdui-dialog-tips .mdui-dialog-tips-content {
    display: inline-block;
    *display: inline;
    *zoom: 1;
    vertical-align: middle; }

.mdui-dialog-close {
  position: absolute;
  right: 13px;
  top: 8px;
  color: #999;
  font-size: 16px;
  font-weight: 700; }
  .mdui-dialog-close:hover {
    text-decoration: none;
    color: #333; }

.mdui-dialog-head {
  margin-top: -5px;
  padding: 0 60px;
  font-size: 18px;
  color: #333;
  text-align: center; }

.mdui-dialog-body {
  margin-top: 10px;
  padding: 0 60px;
  color: #a1a1a1;
  text-align: center; }

.mdui-dialog-foot {
  margin-top: 30px;
  border-top: #e6e6e6 solid 1px;
  overflow: hidden; }
  .mdui-dialog-foot .mdui-dialog-btn {
    height: 50px;
    margin-left: -1px;
    line-height: 50px;
    color: #0085cf;
    text-align: center; }

.mdui-dialog-btns-inline .mdui-dialog-btn {
  float: left;
  border-left: #e6e6e6 solid 1px; }

.mdui-dialog-btns-inline1 .mdui-dialog-btn {
  width: 100%; }

.mdui-dialog-btns-inline2 .mdui-dialog-btn {
  width: 50%; }

.mdui-dialog-btns-inline3 .mdui-dialog-btn {
  width: 33.3%; }

.mdui-dialog-btns-inline4 .mdui-dialog-btn {
  width: 25%; }

.mdui-dialog-btns-block .mdui-dialog-btn {
  display: block;
  height: 50px;
  margin-top: -1px;
  line-height: 50px;
  border-top: #e6e6e6 solid 1px; }
.mdui-region-wrap {
  zoom: 1; }
  .mdui-region-wrap:after {
    visibility: hidden;
    display: block;
    font-size: 0;
    content: " ";
    clear: both;
    height: 0; }

.mdui-region-icon-arrow {
  width: 7px;
  height: 4px;
  position: absolute;
  top: 17px;
  right: 11px;
  background-image: url("//g.mdcdn.cn/pc/img/common/atom_sprite.png"); }

.mdui-region-wrap .mdui-region-section {
  float: left; }

.mdui-region-wrap .mdui-region-city, .mdui-region-wrap .mdui-region-county {
  border-right: 0;
  margin-left: -1px; }

.mdui-region-wrap .mdui-region-section-inner {
  position: relative;
  width: 140px; }

.mdui-region-head {
  cursor: pointer;
  background-color: #fff; }
  .mdui-region-head .mdui-region-icon-arrow {
    background-position: 0 0; }
  .mdui-region-head .mdui-region-selected {
    margin: 0;
    height: 38px;
    line-height: 38px;
    padding: 0 12px;
    border: 1px solid #d6d6d6;
    font-weight: normal;
    -webkit-user-select: none;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis; }

.mdui-region-body {
  width: 138px;
  display: none;
  position: absolute;
  z-index: 100;
  border: 1px solid #d6d6d6;
  border-top: none;
  overflow-y: auto;
  background-color: #fff; }
  .mdui-region-body .mdui-region-option-wrap {
    margin: 0;
    padding: 5px 0;
    max-height: 300px; }
  .mdui-region-body .mdui-region-option {
    cursor: pointer;
    list-style-type: none;
    height: 26px;
    line-height: 26px;
    padding: 0 12px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis; }
  .mdui-region-body .mdui-region-option-hover {
    background-color: #f5f5f5; }

.mdui-region-select-on .mdui-region-icon-arrow {
  background-position: -10px 0; }

.mdui-region-select-on .mdui-region-body {
  display: block; }
@charset "UTF-8";
/**
 * PC 订单确认页
 * @author: byends
 */
/*
SCSS variables are information about icon's compiled state, stored under its original file name

.icon-home {
  width: $icon-home-width;
}

The large array-like variables contain all information about a single icon
$icon-home: x y offset_x offset_y width height total_width total_height image_path;

At the bottom of this section, we provide information about the spritesheet itself
$spritesheet: width height image $spritesheet-sprites;
*/
/*
The provided mixins are intended to be used with the array-like variables

.icon-home {
  @include sprite-width($icon-home);
}

.icon-email {
  @include sprite($icon-email);
}

Example usage in HTML:

`display: block` sprite:
<div class="icon-home"></div>

To change `display` (e.g. `display: inline-block;`), we suggest using a common CSS class:

// CSS
.icon {
  display: inline-block;
}

// HTML
<i class="icon icon-home"></i>
*/
/*
The `sprites` mixin generates identical output to the CSS template
  but can be overridden inside of SCSS

@include sprites($spritesheet-sprites);
*/
.icon_add, .icon_arrow_blue_bottom, .icon_arrow_blue_top, .icon_arrow_bottom, .icon_arrow_left, .icon_arrow_right, .icon_arrow_top, .icon_arrow_white_bottom, .icon_arrow_white_top, .icon_check_disabled, .icon_checked, .icon_distributor, .icon_minus, .icon_minus_gray, .icon_official, .icon_plus, .icon_plus_gray, .icon_unchecked {
 }

.icon_add {
  background-position: -17px 0px;
  width: 16px;
  height: 16px; }

.icon_arrow_blue_bottom {
  background-position: -29px -34px;
  width: 8px;
  height: 5px; }

.icon_arrow_blue_top {
  background-position: -18px -44px;
  width: 8px;
  height: 5px; }

.icon_arrow_bottom {
  background-position: -38px -34px;
  width: 8px;
  height: 5px; }

.icon_arrow_left {
  background-position: -51px -9px;
  width: 5px;
  height: 8px; }

.icon_arrow_right {
  background-position: -51px 0px;
  width: 5px;
  height: 8px; }

.icon_arrow_top {
  background-position: 0px -44px;
  width: 8px;
  height: 5px; }

.icon_arrow_white_bottom {
  background-position: -9px -44px;
  width: 8px;
  height: 5px; }

.icon_arrow_white_top {
  background-position: -20px -34px;
  width: 8px;
  height: 5px; }

.icon_check_disabled {
  background-position: -17px -17px;
  width: 16px;
  height: 16px; }

.icon_checked {
  background-position: 0px 0px;
  width: 16px;
  height: 16px; }

.icon_distributor {
  background-position: 0px -17px;
  width: 16px;
  height: 16px; }

.icon_minus {
  background-position: -30px -40px;
  width: 9px;
  height: 1px; }

.icon_minus_gray {
  background-position: -20px -40px;
  width: 9px;
  height: 1px; }

.icon_official {
  background-position: -34px -17px;
  width: 15px;
  height: 15px; }

.icon_plus {
  background-position: -10px -34px;
  width: 9px;
  height: 9px; }

.icon_plus_gray {
  background-position: 0px -34px;
  width: 9px;
  height: 9px; }

.icon_unchecked {
  background-position: -34px 0px;
  width: 16px;
  height: 16px; }

.address-box, .confirm-order-box .shop-header, .confirm-order-box .goods-wrap, .confirm-order-box .item-num .num_box, .confirm-order-box .shop-total-wrap, .amount-wrap .amount-inner .amount-table, .amount-wrap .amount-inner .order-submit-box {
  zoom: 1; }
  .address-box:after, .confirm-order-box .shop-header:after, .confirm-order-box .goods-wrap:after, .confirm-order-box .item-num .num_box:after, .confirm-order-box .shop-total-wrap:after, .amount-wrap .amount-inner .amount-table:after, .amount-wrap .amount-inner .order-submit-box:after {
    visibility: hidden;
    display: block;
    font-size: 0;
    content: " ";
    clear: both;
    height: 0; }

.container i, .wrap-header h3, .address-box .adr-body .adr-detail, .item-box-btn-save, .item-box-btn-cancel, .coupon-tag, .confirm-order-box .item-num .num_box > span, .confirm-order-box .shop-total-wrap > div {
  display: inline-block;
  *display: inline;
  *zoom: 1; }

textarea, input {
  font-family: "Lucida Grande", Arial, \5FAE\8F6F\96C5\9ED1, \5b8b\4f53;
  outline: none; }

body {
  background-color: #f4f4f4; }

.ms-controller {
  display: none; }

.container {
  width: 1190px;
  margin: auto;
  line-height: 12px; }
  .container .text-orange {
    color: #ff6600; }
  .container .text-black {
    color: #000; }
  .container .text-gray {
    color: #999; }
  .container .text-red {
    color: #f30; }
  .container .text_center {
    text-align: center; }
  .container .loading-wrap {
    width: 330px;
    margin: 100px auto;
    padding: 30px;
    font-size: 14px;
    text-align: center;
    border: 1px solid #e9e9e9;
    background-color: #fff;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px; }

.wrap-header h3 {
  font-size: 24px;
  line-height: 24px;
  font-weight: 400;
  color: #333;
  margin-right: 15px; }

.wrap-header .small-text {
  font-size: 12px;
  color: #999; }

.wrap-header .right-text {
  float: right;
  position: relative;
  top: 12px;
  *top: -12px;
  font-size: 12px;
  color: #333; }

.wrap-header .icon_arrow_bottom {
  position: relative;
  top: -2px;
  right: 1px;
  margin-left: 6px; }

.wrap-header .icon_arrow_right {
  margin-left: 5px; }

.address-wrap {
  margin-top: 40px; }

.address-box {
  margin-top: 20px; }
  .address-box .adr {
    float: left;
    margin-top: -1px;
    margin-left: -1px;
    background-color: #fff;
    cursor: pointer; }
  .address-box .hover {
    background-color: #fafafa; }
    .address-box .hover .adr-foot {
      display: block; }
  .address-box .adr-inner {
    position: relative;
    width: 256.25px;
    height: 75px;
    padding: 20px;
    border: 1px solid #e9e9e9;
    color: #999; }
    .address-box .adr-inner .icon_checked {
      position: absolute;
      top: -2px;
      right: -2px;
      display: none; }
  .address-box .adr-head {
    font-size: 0; }
    .address-box .adr-head .adr-name {
      margin-left: 12px; }
    .address-box .adr-head span {
      font-size: 14px;
      line-height: 14px; }
  .address-box .adr-body {
    margin-top: 10px;
    font-size: 0; }
    .address-box .adr-body .adr-detail {
      margin-right: 8px; }
    .address-box .adr-body span {
      font-size: 12px;
      line-height: 17px; }
  .address-box .adr-default-text {
    margin-left: 6px;
    display: none; }
  .address-box .adr-foot {
    display: none;
    position: absolute;
    bottom: 10px;
    left: 20px; }
    .address-box .adr-foot a {
      color: #0093d9;
      margin-right: 5px; }
  .address-box .checked .adr-inner {
    border: 2px solid #0092d8;
    padding: 19px;
    color: #333;
    z-index: 1; }
  .address-box .checked .adr-foot {
    bottom: 9px;
    left: 19px; }
  .address-box .checked .icon_checked {
    display: inline-block; }
  .address-box .adr-default-text {
    display: none; }
  .address-box .default .adr-default-text {
    display: inline-block; }
  .address-box .adr-add {
    text-align: center; }
    .address-box .adr-add .adr-add-icon {
      margin-top: 18px;
      margin-bottom: 10px; }

```
