### ISSUE TITLE
avalon2 组件疑惑

### ISSUE THREAD

**Issue by qw4wer** [RubyLouvre/avalon#1461]
__使用版本/*! built in 2016-6-11:11 version 2.08 by 司徒正美 */__

按照git上面的例子和easyui的样式写了个tabs组件。
实现了基本的添加、删除、滚动tab的功能。

__现在遇到几个问题和疑惑__

1. 组件定义的方法是否只能在组件模版内部使用？如果这样如何真正做到封装？
2. 组件渲染后，每次更改数据都会全部重新渲染，如何规避或者关闭这个功能？

    基于问题2，主要是因为使用了iframe 去加载页面，那在添加tab时，会初始化所以的iframe，导致之前打开的tab都失去原有的浏览进度。或者要修改某个tab的标题，如何做到只更新某个属性？

__详细代码如下__

```javascript
/**
 * Created by qw4wer on 2016/6/9.
 */

function heredoc(fn) {

    return fn.toString().replace(/^[^\/]+\/\*!?\s?/, '').replace(/\*\/[^\/]+$/, '').trim().replace(/>\s*</g, '><')
}
var tmpl = heredoc(function () {
    /*
     <div class="ms-tab">
     <div class="tabs-scroller-left"  ms-visible="@toggle" ms-click="@scrol('left')" ></div>
     <div class="tabs-scroller-right" ms-visible="@toggle" ms-click="@scrol('right')"></div>
     <div ms-class="['tabs-warp',@toggle?'tabs-margin':'' ]">
     <ul  ms-class="['tabs']" >
     <li ms-for="($index, tab) in @tabs" ms-class="['tab', $index==@currentTab?'current':'' ]"   >
     <p ms-text="tab.name" ms-click="@onChangeTab($index)"></p>
     <a class="tabs-close" ms-click="@onClose($index)"></a>
     </li>
     </ul>
     </div>
     <div class="tabs-panels">
     <div ms-for="($index, tab) in @tabs" class="panel" ms-visible="$index==@currentTab">
     <iframe style="width:100%;height:99%;" scrolling="auto" frameborder="0" ms-attr="{src:tab.component}"></iframe>
     </div>
     </div>
     </div>
     */
})
avalon.component('ms-tabs', {
    template: tmpl,
    defaults: {
        tabs: [],
        tpl: '',
        currentTab: 0,
        component: '',
        tabWidth: 0,
        toggle: false,
        onChangeTab: function (index) {
            this.currentTab = index;
            /*this.tpl = '<p>' + this.tabs[index].component + '</p>';*/
        },
        onInit: function () {
            var index = this.currentTab;
            /*  for (var i = 0; i < this.tabs.length; i++) {
             this.tabWidth += (calc(this.tabs[i].name) * 14 + 8);
             }*/
            setTimeout(function () {
                $("li").each(function () {
                    this.tabWidth += $(this).outerWidth(true);
                });
            }, 0)

            this.onChangeTab(index);
        },
        onClose:function(index){
            this.tabs.splice(index,1);
        },
        calcWidth: function (str) {
            return calc(str) * 14 +5 + "px";
        },
        scrol: function (direction) {
            debugger;
            tabs = $(this.$element).find(".tabs-warp");
            switch (direction) {
                case 'left':
                    tabs.scrollLeft(tabs.scrollLeft() - 200);
                break;
                case 'right' :
                {
                    n = tabs.scrollLeft();
                    if ((vm.config.tabWidth - n - this.$element.offsetWidth) < 200) {
                        tabs.scrollLeft((vm.config.tabWidth - this.$element.offsetWidth) + parseInt($(this.$element).find('.tabs-warp').css('margin-left')) * 2);
                    } else {
                        tabs.scrollLeft(n + 200);
                    }

                }
                break;


            }


        }
    }

})


function calc(str) {
    var reg = /[\u4e00-\u9fa5]/;

    var realLength = new Number(0.0);
    for (var i = 0; i < str.length; i++) {
        var char = str.substring(i, i + 1);
        realLength = reg.test(char) ? realLength + 1 : realLength + 0.5

    }

    return realLength + 1;
}


```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" class="library"  href="../css/tabs.css">
    <script src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="../js/avalon.js"></script>
    <script type="text/javascript" src="../js/tabs.js"></script>
<script type="text/javascript">

    $(document).ready(function(){

        vm = avalon.define({
            $id: 'widget',

            config: {
                tabs: [{
                    name: '标签中文测试a01',
                    component: 'http://www.baidu.com'
                },{
                    name: '标签中文测试a02',
                    component: 'http://www.baidu.com'
                }],
                tabWidth: 0,
                toggle: false,
                currentTab:1
            },
            add: function (obj) {
                this.config.tabs.push(obj);
                tabWidth = 0
                $("li").each(function(){
                    tabWidth += $(this).outerWidth(true);
                });
                this.config.tabWidth = tabWidth;
                /*this.config.tabWidth += calc(obj.name) * 14 +6 ;*/

                if (this.config.tabWidth > this.$element.offsetWidth)
                    this.config.toggle = true;
            },
        });
    })



    function add() {

        vm.add({
            name: '标签中文测试a' + ((vm.config.tabs.length + 1) <10 ? ('0'+(vm.config.tabs.length + 1)) :(vm.config.tabs.length + 1)),
            component:'http://www.sina.com.cn'
        });

        /*vm.add1();*/
    }

</script>
</head>
<body>
<div id="box" ms-controller='widget' >
    <ms-tabs ms-widget="@config"></ms-tabs>
</div>

<input type ="button" onClick="add()" value="add">
</body>
</html>
```

```css

body{
    padding: 0px;
    margin: 0px;

}

#box{
    padding: 0px;
}
.ms-tab *{
    margin:0;
    padding: 0}
.ms-tab ul,.ms-tab li{
    list-style: none;
}
.ms-tab .tabs {
    font-size:0;
    z-index: 10;
    width: 5000px;
    overflow: hidden;
   /* display: inline-block;*/
}
.ms-tab .panel{
    width: auto;

    margin-top: -1px;
    border:1px solid #5b5b5b;

    padding: 0px;
    background:#e6e6e6;
}
.tab{
    display: inline-block;
    font-size:14px;
    height: 30px;
    line-height:30px;

    text-align: center;
    margin-right: 6px;
    border:1px solid #5b5b5b;
    cursor: pointer;

    float: left;
    margin-bottom: -1px;
    padding: 0;
    position: relative;
    -moz-border-radius: 5px 5px 0 0;
    -webkit-border-radius: 5px 5px 0 0;
    border-radius: 5px 5px 0 0;
}
.tab.current{
    background:#e6e6e6;
    color: #666;
    font-weight:800;
    border-bottom: 1px solid #e6e6e6;
}
.tabs-warp{
    position: relative;
    left: 0px;
    overflow: hidden;
    margin: 0px;
    padding: 0px;
}
.tabs-scroller-left {
    position: absolute;
    left: 0px;

    width: 18px;

    height: 30px;
    border: 1px solid #524b4f;
    font-size: 1px;
    display: none;
    cursor: pointer;
    background: #bfbcb9 url(images/retreat.png)  no-repeat center center;
}

.tabs-scroller-right {
    position: absolute;
    right: 0;

    width: 18px;

    height: 30px;
    border: 1px solid #524b4f;
    font-size: 1px;
    display: none;
    cursor: pointer;
    background: #bfbcb9 url(images/advance.png)  no-repeat center center;


}

.tabs-margin{
    margin-left: 20px;
    margin-right: 20px;
}

.tabs-close{
    width: 11px;
    height: 11px;    position: absolute;
    font-size: 1px;
    display: block;
    padding: 0px;
    top: 9px;
    right: 5px;
    opacity: 0.6;
    background: #d2cdcd  url(images/close.png)  no-repeat center center;
}

.ms-tab p{
    white-space: nowrap;
    padding-right: 18px;
}

.tabs-panels{

}
```
