### ISSUE TITLE
数组元素绑定ms-on-transitionend事件问题

### ISSUE THREAD

**Issue by weeksun23** [RubyLouvre/avalon#1701]
浏览器：最新chrome
avalon版本：avalon.modern.js built in 2016-8-20:11 version 2.112 by 司徒正美
描述：本人在做一个toast组件，当调用组件的open方法时就会以动画效果展示一个消息框，一段时间后自动淡出销毁。发现当快速多次点击调用消息框时，会有一些消息框冗余没有被销毁掉，经调试发现是transitionend事件没有被触发，但是慢速点击调用时就没有这问题，具体代码如下：

avalon.toast.css
```css
.toast{
  width: 12em;position: fixed;
  left: 50%;margin-left: -6em;bottom: 8em;z-index: 300;
}
.toast-item{
	position: absolute;left: 0;top: 0;right: 0;
	padding: 0.8em 0;background-color: #333;border-radius: 5px;color: #fff;opacity: 0;text-align: center;
	transform : translate3d(0,100%,0);
  -webkit-transform : translate3d(0,100%,0);
  transition: all 0.8s;
  -webkit-transition: all 0.8s;
}
.toast-item-show{
  transform : translate3d(0,0,0);
  -webkit-transform : translate3d(0,0,0);
  opacity : 1;
}
.toast-item-hide{
	opacity: 0;
}
```
avalon.toast.html
```html
<div class='toast' :visible='@_isShow'>
	<div class='toast-item' :for='($index,el) in @items' :class='{"toast-item-show" : el.toastItemShow,
		"toast-item-hide" : el.toastItemHide}' :on-transitionend='@_transitionend(el,$event)'>{{el.text}}</div>
</div>
```
avalon.toast.js
```javascript
define(function(require){
	require("./avalon.toast.css");
	var tpl = require("./avalon.toast.html");
	avalon.component("ms-toast",{
		template : tpl,
		defaults : {
			_isShow : false,
			_transitionend : function(el,e){
				if(e.propertyName !== 'opacity') return;
				console.log(el.text);
				if(el.toastItemHide){
					this.items.remove(el);
					if(this.items.length === 0){
						this._isShow = false;
					}
				}else{
					setTimeout(function(){
						el.toastItemHide = true;
					},800);
				}
			},
			items : [],
			open : function(msg){
				var items = this.items;
				if(items.length === 0) this._isShow = true;
				items.push({
					toastItemShow : false,
					text : items.length + 1,
					toastItemHide : false
				});
				var index = items.length - 1;
				var target = items[index];
				//reflow
				avalon(this.$element).children(index).offsetWidth;
				target.toastItemShow = true;
			}
		}
	});
});
```
测试页面代码
```html
<body ms-controller="body">
	<button ms-click="@show">show</button>
	<template :widget="{is:'ms-toast',$id:'toast'}"></template>
	<script src="../../lib/seajs/sea.js"></script>
	<script src="../avalon.modern.js"></script>
	<script>
		//获取所有子元素，非文本节点
		avalon.fn.children = function(i){
			var children = [];
			avalon.each(this[0].childNodes,function(i,node){
				node.nodeType === 1 && children.push(node);
			});
			if(i !== undefined){
				return children[i];
			}
			return children;
		};
		seajs.config({
      base : "../../"
    });
    seajs.use(["avalon/toast/avalon.toast"],function(){
    	avalon.define({
    		$id : "body",
    		show : function(){
    			avalon.vmodels.toast.open('testtest');
    		}
    	});
    	avalon.scan(document.body);
    });
	</script>
</body>
```
