### ISSUE TITLE
使用 avalon 如何避免先展示，而后才扫描再展示？

### ISSUE THREAD

**Issue by treenew** [RubyLouvre/avalon#863]
无论放在 head 还是放在 body最后，依然会出现（先渲染并展示 html）。不知道有没有什么最佳的解决办法？？

**Comment by weeksun23** [comment]
```css
[ms-controller],[ms-important]{display:none !important;}
```

**Comment by treenew** [comment]
你这么牛逼，你妈妈知道吗？给你一百个赞！！！

**Comment by LittleFoolfish** [comment]
看来你不太关注原api~

**Comment by treenew** [comment]
楼上是啥意思？原 API？

**Comment by weeksun23** [comment]
http://avalonjs.github.io/#zh/bindings/controller.html
```css
.ms-controller,.ms-important,[ms-controller],[ms-important]{
     visibility: hidden;
 }
```
请认真阅读API吧
